export root_dev="sda3"
export efi_dev="sda2"
export mp="/mnt/root"
export boot_dev=""
export rescue_dev="sda1"
export keyslot_size="32m"
export enlarge=no
export swap_zize="4G"
export grub_efi_dev="(hd0,gpt2)"
export hide_grub_menu="yes" #hold shift during boot
export btrfs_options="defaults,ssd,discard=async,noatime,space_cache=v2,compress=zstd:1"
export installation_type="install_other"
export suite="ubuntu"
export suite_type="minimal"
export PASSPHRASE="password"
export pre_download="yes"
export root_sub_vol="@$suite"
export sb_key_dir="/mnt/root/@ubuntu/var/lib/sbctl"