export root_dev="sda3"
export efi_dev="sda2"
export mp="/mnt/root"
export rescue_dev="sda1"
export keyslot_size="32m"
export enlarge=no
export swap_size="4G"
export btrfs_options="defaults,ssd,discard=async,noatime,space_cache=v2,compress=zstd:1"
export suite="ubuntu"
export suite_type="minimal"
export PASSPHRASE="password"
export pre_download="yes"
export root_sub_vol="@$suite"
export sb_key_dir="/mnt/root/@ubuntu/var/lib/sbctl"
export root_uuid="$(blkid --output export /dev/"$root_dev" | grep ^UUID=)"

export repository_root=~/ubuntu-btrfs-on-root