#!/usr/bin/env bash

set -e


# https://github.com/paadza/Ubuntu-encrypted-btrfs-with-and-home-subvolumes-swap-and-Timeshift
# https://gist.github.com/TheHarold/27d87e9e027718a0f60db7ff04c4d104
# https://medium.com/@inatagan/installing-debian-with-btrfs-snapper-backups-and-grub-btrfs-27212644175f
# https://github.com/wmutschl/timeshift-autosnap-apt
# https://dev.to/achu1612/disk-encryption-using-luks-and-tpm20-19hb
# https://www.jwiltshire.org.uk/2025/01/07/using-tpm-for-automatic-disk-decryption-in-debian-12/
# https://www.reddit.com/r/Ubuntu/comments/1skdqc3/tpmbacked_full_disk_encryption_2510_vs_2604/
# https://github.com/Antynea/grub-btrfs/issues/399
#https://wiki.archlinux.org/title/GRUB/Tips_and_tricks
#https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#Encrypted_boot_partition_(GRUB)
#https://www.systemshardening.com/articles/linux/uki-secure-boot-hardening/

#scriptpath="$(dirname "$script")"

[[ "$(id -u)" -eq 0 ]] || { echo "ERROR: Must be run as root."; exit 1; }

script="$(readlink -f "$0")"
scriptname="$(basename "$script")"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
script_dir_name="$(basename "$script_dir")"



# shellcheck source=./setup.conf
. "$script_dir/setup.conf"

root_uuid="$(blkid --output export /dev/"$root_dev" | grep ^UUID=)"

preparation() {
	echo -e "\e[32mINFO:\e[0mPrepare"
	
	umount /target/boot/efi
	umount /target/cdrom
	umount /target

	mkdir $mp
}



prepare_chroot() {
	echo -e "\e[32mINFO:\e[0mPrepare $mp for chroot"  
	mount --rbind /dev "$mp/dev"
    mount --make-rslave "$mp/dev"

    mount -t proc proc "$mp/proc"
	mount -t devpts pts $mp/dev/pts

    mount --rbind /sys "$mp/sys"
    mount --make-rslave "$mp/sys"

    mount -t tmpfs tmpfs "$mp/run"
	
	mount -o subvol=$root_sub_vol/@home /dev/mapper/root $mp/home
	
	mount /dev/$efi_dev $mp/boot/efi
	mkdir -p $mp/sys/firmware/efi/efivars && mount --bind /sys/firmware/efi/efivars $mp/sys/firmware/efi/efivars

	#mount --rbind /run "$mp/run"
	#mount --make-rslave "$mp/run"
	mount -t tmpfs tmpfs "$mp/run"
	mkdir -p "$mp/run/dbus"

    # Preserve target's resolv.conf
    if [[ -e "$mp/etc/resolv.conf" || -L "$mp/etc/resolv.conf" ]]; then
        mv "$mp/etc/resolv.conf" "$mp/etc/resolv.conf.chroot-save"
    fi

    cp /run/systemd/resolve/resolv.conf "$mp/etc/resolv.conf"
	cat > $mp/etc/resolv.conf <<- 'EOF'
		nameserver 1.1.1.1
		nameserver 8.8.8.8
	EOF

    # Prevent packages from starting/stopping services
    cat > "$mp/usr/sbin/policy-rc.d" <<- 'EOF'
		#!/bin/sh
		exit 101
	EOF
    chmod 755 "$mp/usr/sbin/policy-rc.d"
}


chroot_and_mkinitramfs() {
	cp -Rf "$script_dir" "$mp/root/"
	chmod a+x "$mp/root/$script_dir_name/$scriptname"
	echo -e "\e[32mINFO:\e[0mChrooting and call the script in the other root"
	unshare --mount --fork chroot $mp /root/"$script_dir_name/$scriptname" //inner
}


suite_selction(){
	
	case $suite_type in
		minimal)
			exit
			;;
		deskop)
			apt install -y mythes-en-au mythes-en-us  \
				thunderbird-locale-en thunderbird-locale-en-gb thunderbird-locale-en-us \
				ubuntu-desktop ubuntu-restricted-addons wbritish \
				libreoffice-help-common libreoffice-help-en-gb libreoffice-help-en-us libreoffice-l10n-en-gb libreoffice-l10n-en-za \
				open-vm-tools-desktop openssh-server

			exit
			;;
		server)
			exit
			;;
	esac


}

pre_download_all(){
	
	#apt install -y --download-only refind build-essential snapper inotify-tools cryptsetup-initramfs libtasn1-6 libdevmapper1.02.1 \
	#	libc6 libselinux1 libudev1 libpcre2-8-0 gawk git make asciidoc-base pkgconf pkgconf-bin curl jq \
	#	libpcsclite-dev libpcsclite1 golang-go sbsigntool tpm2-tools tpm2-tss libtss2-esys-3.0.2-0t64 libtss2-mu-4.0.1-0t64 libtss2-rc0t64 libtss2-tcti-tabrmd0
	apt install --no-install-recommends -y --download-only btrfs-assistant btrfsmaintenance
	
	apt install --download-only -y refind snapper inotify-tools cryptsetup-initramfs \
	dracut \
    dialog \
    systemd-ukify \
    binutils \
    rsync \
    openssl \
	systemd-cryptsetup \
    cryptsetup-bin \
	tpm2-tools tpm2-tss libtss2-esys-3.0.2-0t64 libtss2-mu-4.0.1-0t64 libtss2-rc0t64 libtss2-tcti-tabrmd0 build-essential  fwupd-unsigned  git \
	ca-certificates \
        findutils \
        coreutils \
		fwupd \
        efibootmgr \
        sbsigntool \
        findutils \
        coreutils \
        ca-certificates \
		fwupd-unsigned \
		ca-certificates \
        efibootmgr \
        sbsigntool \
        dosfstools \
        util-linux \
        findutils \
        coreutils \
		asciidoc-base \
    pkgconf \
    pkgconf-bin \
    curl \
    jq \
    libpcsclite-dev \
    libpcsclite1 \
    golang-go \
    sbsigntool \
    git \
    build-essential \
    pcscd \
    fwupd-unsigned
	
	#apt install -y asciidoc-base pkgconf pkgconf-bin curl libpcsclite-dev libpcsclite1 golang-go sbsigntool pcscd  
	#go install github.com/foxboron/sbctl/cmd/sbctl@latest
	
	
	apt install -y openssh-server open-vm-tools-desktop
	#apt install -y --download-only mythes-en-au mythes-en-us  \
	#			thunderbird-locale-en thunderbird-locale-en-gb thunderbird-locale-en-us \
	#			ubuntu-desktop ubuntu-restricted-addons wbritish \
	#			libreoffice-help-common libreoffice-help-en-gb libreoffice-help-en-us libreoffice-l10n-en-gb libreoffice-l10n-en-za \
	#			open-vm-tools-desktop openssh-server

}

# ------------------------------
# Inner chroot execution
# ------------------------------

if [[ "$1" = "//inner" ]]; then
	
	dbus-daemon --system --fork
	cd ~/ubuntu-btrfs-on-root
	. ./setup.conf

	rm -rf /boot/efi/EFI/$suite	
	apt-get update
	if [[ $pre_download = "yes" ]]; then
		pre_download_all
	fi
	. ./btrfs-root/scripts/btrfs-root-setup
	. ./secure-boot/scripts/secure-boot-setup
	. ./btrfs-snapshots-mng/scripts/btrfs-snapshots-mng-setup
	. ./uki/scripts/install-uki

	exit

fi


# ------------------------------
# Help
# ------------------------------

show_help() {
	echo "Add @ and @home subvolumes to a Btrfs root partition,"
	echo "and encrypt it optionally"
	echo
	echo "Usage: btrfs-encrypt-root [options] {root-dev} {boot-dev} [{efi-dev}]"
	echo
	echo "The devices must be given without the /dev/ prefix."
	echo
	echo "  --only-subvols            do not encrypt, only create @ and @home"
	echo "  --enlarge                 enlarge root partition to maximum"
	echo
	echo "--enlarge resizes the root partition to 100%. This makes encryption"
	echo "much faster, because you make a small partition for just the"
	echo "installation of the base system, and then you call this script,"
	echo "which has to encrypt only the smaller partition. The enlargement"
	echo "covers only empty space, so no encryption is necessary there."
}

# ------------------------------
# Parse arguments
# ------------------------------


while :; do
	case "$1" in
		-h|-\?|--help)
			show_help
			exit
			;;
		--setup-tpm-luks-auto_ulock)
			tpm_enroll
			exit
			;;
		--seal-luks-disk-tpm)
			tpm_reseal
			exit
			;;
		--*)
			echo "Invalid option $1. Use --help for more information."
			exit 2
			;;
		*)
			break
	esac
	shift
done

unmount_everything() {
    local root="${mp}"
    local lazy_fallback="${2:-false}"
    local target
    local i
    local failed=0

	

    [[ -e "$root" ]] || return 0

	rm -f "$root/usr/sbin/policy-rc.d"

    rm -f "$root/etc/resolv.conf"
    if [[ -e "$root/etc/resolv.conf.chroot-save" ||
          -L "$root/etc/resolv.conf.chroot-save" ]]; then
        mv "$root/etc/resolv.conf.chroot-save" "$root/etc/resolv.conf"
    fi

    mapfile -t mounts < <(
        findmnt -Rrn -o TARGET "$root" 2>/dev/null
    )

    ((${#mounts[@]})) || return 0

    for ((i = ${#mounts[@]} - 1; i >= 0; i--)); do
        target="${mounts[i]}"

        mountpoint -q "$target" || continue

        echo "Unmounting: $target"

        if umount "$target"; then
            continue
        fi

        echo "Retrying: $target" >&2
        sync

        sleep 0.2

        if umount "$target"; then
            continue
        fi

        if [[ "$lazy_fallback" == true ]]; then
            echo "Lazy unmount: $target" >&2

            if umount -l "$target"; then
                continue
            fi
        fi

        echo "ERROR: unable to unmount $target" >&2
        failed=1
    done
	sleep 2
	cryptsetup close root
}

if [[ -z $PASSPHRASE ]]; then
	echo "You must pass the PASSPHRASE of the root volume to encrypt"
	echo
	echo "Use --help for more information."
	exit 2
fi


# ------------------------------
# Main execution
# ------------------------------

preparation
. ./btrfs-root/scripts/btrfs-root-setup
prepare_chroot
chroot_and_mkinitramfs
unmount_everything

echo "Finished"

