#!/usr/bin/env bash

set -Eeuo pipefail


# ============================================================
# Configuration
# ============================================================

ESP="${ESP:-/boot/efi}"
REFIND_EFI="$ESP/EFI/refind"
SETUP_MODE="${SETUP_MODE:-}"

# ============================================================
# sbctl signing
# ============================================================

sign_efi()
{
    local file="$1"

    [[ -f "$file" ]] ||
        die "EFI file not found: $file"

    log "Signing with sbctl:"
    log "  $file"

    sbctl sign \
        --save \
        "$file"
}

sign_refind()
{
    local refind="$REFIND_EFI/refind_x64.efi"

    sign_efi "$refind"

    if [[ -d "$REFIND_EFI/drivers_x64" ]]; then

        while IFS= read -r -d '' driver
        do
            sign_efi "$driver"

        done < <(
            find "$REFIND_EFI/drivers_x64" \
                -maxdepth 1 \
                -type f \
                -name '*.efi' \
                -print0
        )
    fi
}


# ============================================================
# Sign fwupd EFI with sbctl
# ============================================================

sign_fwupd_efi()
{
    require_command sbctl
    require_file "$DB_KEY"
    require_file "$DB_CERT"
    require_file "$FWUPD_EFI"

    log "Signing fwupd EFI with sbctl:"
    log "  $FWUPD_EFI"

    sbctl sign \
        --save \
        "$FWUPD_EFI"
}


# ============================================================
# Verify signature
# ============================================================

verify()
{
	local refind="$REFIND_EFI/refind_x64.efi"

    [[ -f "$refind" ]] ||
        die "rEFInd EFI binary not found."

    log "Checking rEFInd signature..."

    if sbverify --cert /var/lib/sbctl/keys/db/db.pem "$refind"; then
        echo "✅ sbverify verification passed"
    else
        echo "❌ sbverify verification failed"
    fi

    if [[ "$SETUP_MODE" == "0" ]]; then

        [[ -f "$REFIND_EFI/shimx64.efi" ]] ||
            die "Shim missing from rEFInd directory."

        [[ -f "$REFIND_EFI/mmx64.efi" ]] ||
            die "MokManager missing from rEFInd directory."
    fi
	
    log "Verifying fwupd EFI signature..."

    if sbverify --cert /var/lib/sbctl/keys/db/db.pem "$FWUPD_EFI"; then
        echo "✅ sbverify verification passed"
    else
        echo "❌ sbverify verification failed"
    fi
}

#
# Do NOT touch shimx64.efi or mmx64.efi.
#
# Sign only rEFInd and its drivers.
#
sign_refind
sign_fwupd_efi
verify
