ROOT_SUBVOL="@ubuntu"
SNAPSHOT_DIR=".snapshots"

TTY="/dev/tty1"

MOUNTPOINT="/run/snapshot-menu-root"
RESULT="/run/snapshot-menu-selected"

CMDLINE_DIR="/etc/cmdline.d"
SNAPSHOT_CMDLINE="/etc/cmdline.d/99-snapshot.conf"
