#!/usr/bin/env bash
set -Eeuo pipefail

script="$(readlink -f "$0")"
scriptname="$(basename "$script")"

repository_root="$(
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." &&
        pwd
)"

source $repository_root/setup.conf

[[ $EUID -eq 0 ]] || {
    echo "Run $scriptname as root." >&2
    exit 1
}

echo -e "\e[32mINFO:\e[0mInstall rEFInd Bootloader"
	
root_uuid="$(blkid --output export /dev/"$root_dev" | grep ^UUID=)"

echo "refind refind/install_to_esp boolean true" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt install -y refind

cp /usr/share/refind/refind/drivers_x64/{btrfs,iso9660,ext2,ext4}_x64.efi /boot/efi/EFI/refind/drivers_x64/

unzip $repository_root/refind/refind_themes.zip -d /boot/efi/EFI/refind/
			
cat >> /boot/efi/EFI/refind/refind.conf <<-EOF
	#scanfor external,optical,manual
	also_scan_dirs EFI/Linux/$suite
	dont_scan_dirs EFI/$suite,EFI/systemd
	dont_scan_files shimx64.efi,grubx64.efi,mmx64.efi,fbx64.efi
	enable_touch
	enable_mouse
	use_graphics_for osx,linux
	include themes/refind-theme-regular/theme.conf

    menuentry "Ubuntu Linux (Grub-btrfs)" {
		volume "Ubuntu 26.04.0 RESCUE amd64"
		loader /EFI/boot/bootx64.efi
		#icon /EFI/refind/themes/refind-theme-regular/icons/256-96/tool_apple_rescue.png
		ostype Linux
		disabled
	}
EOF


for f in btrfs_x64.efi iso9660_x64.efi ext2_x64.efi ext4_x64.efi ; do
	sbctl sign -s "/boot/efi/EFI/refind/drivers_x64/$f"
done

sbctl sign -s "/boot/efi/EFI/refind/refind_x64.efi"
sbctl sign -s "/boot/efi/EFI/BOOT/BOOTX64.EFI"
apt-mark hold \
    refind \
    grub-common \
    grub2-common \
    grub-pc \
    grub-pc-bin \
    grub-efi-amd64 \
    grub-efi-amd64-bin
cd /