#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

[[ $EUID -eq 0 ]] || {
    echo "Run install-uki as root." >&2
    exit 1
}

repository_root="$(
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." &&
        pwd
)"

source $repository_root/setup.conf

apt-get install -y \
    dracut \
    dialog \
    systemd-ukify \
    binutils \
    rsync \
    openssl



#read -r -p "Distribution identifier [ubuntu]: " distro_id
#distro_id="${distro_id:-ubuntu}"
#
#[[ "$distro_id" =~ ^[a-z0-9][a-z0-9._-]*$ ]] || {
#    echo "Invalid distribution identifier: $distro_id" >&2
#    exit 1
#}
#
#read -r -p "ESP mount point [/boot/efi]: " esp_directory
#esp_directory="${esp_directory:-/boot/efi}"
#
#mountpoint -q "$esp_directory" || {
#    echo "ESP is not mounted: $esp_directory" >&2
#    exit 1
#}
#
#read -r -p "Btrfs root filesystem UUID: " btrfs_uuid
#
#[[ -n "$btrfs_uuid" ]] || {
#    echo "The Btrfs UUID is required." >&2
#    exit 1
#}
#
#read -r -p "Root LUKS UUID: " luks_uuid
#
#[[ -n "$luks_uuid" ]] || {
#    echo "The LUKS UUID is required." >&2
#    exit 1
#}
#
#read -r -p "Normal root subvolume [@ubuntu]: " root_subvolume
#root_subvolume="${root_subvolume:-@ubuntu}"

distro_id=$suite
esp_directory=/boot/efi
btrfs_uuid="$(blkid --output export /dev/mapper/root | grep ^UUID= | cut -c 6-)"
luks_uuid=$(cryptsetup luksUUID /dev/$root_dev)
root_subvolume=$root_sub_vol/@


install -d -m 0700 /etc/uki/keys


cat >/etc/kernel/install.conf <<-'EOF'
    layout=uki
    initrd_generator=dracut
    uki_generator=ukify
EOF
chmod 0644 /etc/kernel/install.conf

echo $suite > /etc/kernel/entry-token
chmod 0644 /etc/kernel/entry-token

cat > /etc/kernel/uki.conf << 'EOF'
    [UKI]
    PCRBanks=sha256
    OSRelease=@/etc/os-release
    Cmdline=@/etc/kernel/cmdline
    Splash=/usr/share/plymouth/themes/spinner/bgrt-fallback.png

    SecureBootSigningTool=sbsign
    SecureBootPrivateKey=/var/lib/sbctl/keys/db/db.key
    SecureBootCertificate=/var/lib/sbctl/keys/db/db.pem

    SignKernel=false

    PCRPKey=/etc/uki/keys/pcr-public.pem
    
    [PCRSignature:initrd]
    PCRPrivateKey=/etc/uki/keys/pcr-private.pem
    PCRPublicKey=/etc/uki/keys/pcr-public.pem
    Phases=enter-initrd

    [PCRSignature:system]
    Phases=enter-initrd:leave-initrd enter-initrd:leave-initrd:sysinit enter-initrd:leave-initrd:sysinit:ready
    PCRPrivateKey=/etc/uki/keys/pcr-private.pem
    PCRPublicKey=/etc/uki/keys/pcr-public.pem
EOF
chmod 600 /etc/kernel/uki.conf
ln -sf \
    /etc/kernel/uki.conf \
    /etc/systemd/ukify.conf

cat > /etc/dracut.conf.d/53-uki-cmdline.conf <<-'EOF'
    hostonly_cmdline="no"
EOF

if [[ ! -s /etc/uki/keys/pcr-private.pem ]]; then
    openssl genpkey \
        -algorithm RSA \
        -pkeyopt rsa_keygen_bits:2048 \
        -out /etc/uki/keys/pcr-private.pem

    openssl pkey \
        -pubout \
        -in /etc/uki/keys/pcr-private.pem \
        -out /etc/uki/keys/pcr-public.pem
fi

chmod 0600 /etc/uki/keys/pcr-private.pem
chmod 0644 /etc/uki/keys/pcr-public.pem

echo "root=UUID=${btrfs_uuid} rootfstype=btrfs rootflags=${btrfs_options},subvol=${root_subvolume} rd.luks.uuid=luks-${luks_uuid} rd.shell=0 rd.emergency=halt quiet splash" > /etc/kernel/cmdline
chmod 0644 /etc/kernel/cmdline

install -m 0755 \
    "$repository_root/uki/hooks/kernel/postinst.d/debian-kernel-install-bridge" \
    /usr/local/libexec/debian-kernel-install-bridge

ln -sfn \
    /usr/local/libexec/debian-kernel-install-bridge \
    /etc/kernel/postinst.d/zz-kernel-install

ln -sfn \
    /usr/local/libexec/debian-kernel-install-bridge \
    /etc/kernel/postrm.d/zz-kernel-install

if [[ $enable_tpm == "yes" ]]; then
    . $repository_root/tpm/scripts/install-tpm
fi

echo "Installing rEFInd boot manager hook..."
install -m 755 \
	"$repository_root/uki/hooks/kernel/install.d/99-refind-menu.install" \
	/usr/lib/kernel/install.d/99-refind-menu.install
echo "include refind-linux-$suite.conf" >> "/boot/efi/EFI/refind/refind.conf"

install \
    -m 0755 \
    "$repository_root/uki/scripts/generate-uki" \
    /usr/local/sbin/generate-uki

echo
echo "UKI support installed."
echo "UKI destination: ${esp_directory}/EFI/Linux/${distro_id}"

. "$repository_root/uki/scripts/generate-uki" --all
