#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

[[ $EUID -eq 0 ]] || {
    echo "Run btrfs-root-setup as root." >&2
    exit 1
}

source $repository_root/setup.conf

. "$repository_root/btrfs-root/scripts/btrfs-subvol-setup"
. "$repository_root/btrfs-root/scripts/luks-setup"
. "$repository_root/btrfs-root/scripts/fstab-setup"
